---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1716101/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R image $DEPLOYPATH
    - /bin/cp gallery.html $DEPLOYPATH
    - /bin/cp aboutus.html $DEPLOYPATH